Repository GroupeNRM/Youngfood, pull requests merged in 2020-05, with the labels that each got.

#16 Pull Request from Feat/notification Branch
  assets/scss/_form.scss
  assets/scss/_variables.scss
  src/Controller/AdminController.php
  src/Entity/Notification.php
  src/Form/newNotificationType.php
  templates/admin/notification/index.html.twig
Labels: enhancement

#17 remove a dumb bracket
  src/Controller/AdminController.php
Labels: bug

#18 Fix wrong path
  templates/admin/notification/index.html.twig
  templates/dashboard/newchild.html.twig
Labels: bug

#19 Make the menu reusable!
  templates/partials/menu.html.twig
Labels: enhancement

#20 make use of the menu in the existant page
  templates/admin/newFood.html.twig
  templates/admin/notification/index.html.twig
  templates/dashboard/newchild.html.twig
Labels: enhancement

#22 Pull Request optim/move-css Branch
  assets/scss/login.scss
  assets/scss/newchild.scss
  webpack.config.js
Labels: feat

#23 Pull Request feat/info-meal Branch
  src/Controller/AdminController.php
  src/Entity/Food.php
  src/Form/newFoodType.php
  templates/admin/newFood.html.twig
  yarn.lock
Labels: feat

#21 Pull Request from feat/remember-me Branch
  config/packages/security.yaml
Labels: feat

#14 Feature : Add new meal composed of Food :)
  .gitignore
  assets/js/newMeal.js
  assets/scss/_variables.scss
  assets/scss/newMeal.scss
  assets/vue/NewMeal.vue
  assets/vue/Register.vue
  assets/vue/views/newMeal/Food.vue
  assets/vue/views/newMeal/FoodInfoModal.vue
  assets/vue/views/newMeal/Progression-Bar.vue
  composer.json
  composer.lock
  config/services.yaml
  package.json
  public/js/fos_js_routes.json
  src/Controller/AdminController.php
  src/Entity/Food.php
  src/Entity/Meal.php
  src/Form/NewMealType.php
  src/Repository/FoodRepository.php
  src/Repository/MealRepository.php
  templates/admin/newMeal.html.twig
  templates/partials/menu.html.twig
  webpack.config.js
  yarn.lock
Labels: feat

#25 Live notification with Mercure!
  assets/js/dashboard.js
  assets/js/newchild.js
  assets/scss/_menu.scss
  assets/scss/_variables.scss
  assets/scss/dashboard.scss
  assets/vue/Notification.vue
  src/Entity/Notification.php
  src/Repository/NotificationRepository.php
  templates/admin/home/index.html.twig
  templates/admin/newFood.html.twig
  templates/admin/newMeal.html.twig
  templates/admin/notification/index.html.twig
  templates/dashboard/newchild.html.twig
  templates/partials/menu.html.twig
  webpack.config.js
Labels: feat

#24 Pull Request from feat/change password
  assets/js/reset-password.js
  assets/scss/_form.scss
  assets/scss/reset-password.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/reset_password.yaml
  src/Controller/ResetPasswordController.php
  src/Entity/ResetPasswordRequest.php
  src/Form/ChangePasswordFormType.php
  src/Form/ResetPasswordRequestFormType.php
  src/Repository/ResetPasswordRequestRepository.php
  symfony.lock
  templates/reset_password/check_email.html.twig
  templates/reset_password/email.html.twig
  templates/reset_password/request.html.twig
  templates/reset_password/reset.html.twig
  templates/security/login.html.twig
  webpack.config.js
  yarn.lock
Labels: feat

#29 New booking for canteen ! 📅
  assets/js/newBooking.js
  assets/scss/newBooking.scss
  assets/vue/NewBooking.vue
  assets/vue/NewMeal.vue
  package.json
  src/Controller/AdminController.php
  src/Entity/Booking.php
  src/Entity/Meal.php
  src/Repository/BookingRepository.php
  templates/admin/newBooking.html.twig
  webpack.config.js
  yarn.lock
Labels: feat

#28 Pull Request feat/list notification Feature
  assets/js/listNotification.js
  assets/scss/listNotification.scss
  assets/vue/ListNotification.vue
  src/Controller/AdminController.php
  templates/admin/notification/list.html.twig
  webpack.config.js
Labels: feat

#30 Optim the route path and link
  src/Controller/AdminController.php
  src/Controller/DashboardController.php
  src/Controller/SignupController.php
Labels: optim

#31 Pull Request from optim/template Branch
  assets/scss/home.scss
  src/Controller/SecurityController.php
  templates/admin/home/index.html.twig
  templates/admin/notification/index.html.twig
  templates/dashboard/newchild.html.twig
  templates/home/index.html.twig
  templates/partials/footer.html.twig
  templates/partials/menu.html.twig
  templates/security/login.html.twig
  yarn.lock
Labels: bugfix, optim

#33 Pull Request feat/update password Branch
  src/Controller/DashboardController.php
  src/Form/UpdatePasswordType.php
  templates/dashboard/updatepassword.html.twig
Labels: feat

#35 Add favicon and adjust logo size
  assets/img/favicon.png
  assets/scss/home.scss
  templates/base.html.twig
  templates/home/index.html.twig
Labels: feat, optim

#36 Pull Request feat/error-pages Branch
  assets/js/error.js
  assets/scss/error.scss
  templates/bundles/TwigBundle/Exception/error.html.twig
  templates/bundles/TwigBundle/Exception/error403.html.twig
  templates/bundles/TwigBundle/Exception/error404.html.twig
  webpack.config.js
Labels: feat

#38 Move home menu, add "how does youngfood work"
  assets/img/create_meal.gif
  src/Controller/HomeController.php
  templates/home/howItWorks.html.twig
  templates/home/index.html.twig
  templates/partials/top-menu.html.twig
Labels: feat, optim

#40 Feat/youngfood explained
  assets/img/create_meal.gif
  src/Controller/HomeController.php
  templates/home/howItWorks.html.twig
  templates/home/index.html.twig
  templates/partials/top-menu.html.twig
Labels: feat, optim

#41 Update some path, fix minor bugs
  assets/vue/Notification.vue
  assets/vue/Register.vue
  public/js/fos_js_routes.json
  src/Controller/AdminController.php
  src/Controller/DashboardController.php
  src/Controller/HomeController.php
  templates/partials/menu.html.twig
Labels: bugfix, optim

#42 Pull Request feat/user-crud Branch
  assets/js/user.js
  assets/scss/_variables.scss
  assets/scss/user.scss
  src/Controller/AdminController.php
  src/Form/UserType.php
  templates/admin/user/_delete_form.html.twig
  templates/admin/user/edit.html.twig
  templates/admin/user/index.html.twig
  templates/admin/user/new.html.twig
  templates/admin/user/show.html.twig
  templates/partials/menu.html.twig
  webpack.config.js
Labels: feat

#37 Pull Request feat/security Branch
  config/packages/security.yaml
  templates/partials/menu.html.twig
Labels: feat

#43 Hotfix/fix permissions
  src/Controller/AdminController.php
  templates/admin/user/index.html.twig
  templates/dashboard/updatepassword.html.twig
  templates/partials/menu.html.twig
Labels: bugfix
